# Generated by Django 2.2 on 2019-04-28 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCode',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shortcode', serialize=False, to='provider.Service')),
                ('shortcode', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextCode',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='textcode', serialize=False, to='provider.Service')),
                ('textcode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Only number is allowed -- min of 3 and max of 10; no text please', regex='^\\d{3,10}$')])),
                ('message', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='has_shortcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='has_textcode',
            field=models.BooleanField(default=False),
        ),
    ]
