# Generated by Django 2.2 on 2019-05-10 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20190428_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='invalid shortcode: shortcode code must start with * and end with #', regex='^[*#]{1,2}.+[#]{1}$')]),
        ),
    ]
